### ISSUE TITLE
Error: resource spinnaker_pipeline doesn't support import

### ISSUE THREAD

**Issue by xolantumy** [mercari/terraform-provider-spinnaker#71]
## WHAT
I need to import spinnaker pipelines into my terraform remote state

## WHY
I have existing pipelines that I don't want to recreate. When I try with this command:

`terraform import spinnaker_pipeline.pipeline my_app.pipeline` 

I get the following error:

`Error: resource spinnaker_pipeline doesn't support import`

**Comment by KeisukeYamashita** [comment]
Hi @xolantumy, thank you for raising this issue. Sorry for the late reply 🙇 

Importing Spinnaker pipelines and pipeline templates are not supported yet. 
This is because the use the JSON input and not the native HCL. 

But we have a roadmap to support Spinnaker pipeline and pipeline templates with native HCL.
Please wait for our updates.
